CA65 ?= ca65
LD65 ?= ld65

ROOT := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
OUT_DIR := $(ROOT)build
ROM_DIR := $(ROOT)ROMS
PROFILE := $(ROOT)profiles/Apple2eEver2eBootLoopNoSlots.emu
SWITCH_TEST_PROFILE := $(ROOT)profiles/Apple2eBankSwitchChecksumTestNoSlots.emu
JVM_DIR ?= /Users/shane/Project/ever2e-jvm
JVM_P6_TEST_FILTER ?= test.cpu.Cpu65c02CycleTimingTest
JVM_P6_DISK_FILTER ?= test.device.DiskIISlotRomSignatureTest
PY_DIR ?= $(ROOT)testing/ever2e-py
P6_PY_STRICT ?= 0
P6_PY_REPORT ?= /tmp/p6_py_output_report.json

ASM_SRC := \
	$(ROOT)asm/main.asm \
	$(ROOT)asm/babeep.asm \
	$(ROOT)asm/cpu_guard.asm \
	$(ROOT)asm/softswitch_reset.asm \
	$(ROOT)asm/ram_clear_unrolled.asm
OBJ := \
	$(OUT_DIR)/main.o \
	$(OUT_DIR)/babeep.o \
	$(OUT_DIR)/cpu_guard.o \
	$(OUT_DIR)/softswitch_reset.o \
	$(OUT_DIR)/ram_clear_unrolled.o
CFG := $(ROOT)cfg/apple2e_rom16k.cfg
ROM := $(ROM_DIR)/EVER2E.ROM
MAP := $(OUT_DIR)/EVER2E.map
LBL := $(OUT_DIR)/EVER2E.lbl
CHECKSUM_FILE := $(ROM_DIR)/checksum.txt
SWITCH_TEST_SRC := $(ROOT)asm/bank_switch_checksum_test.asm
SWITCH_TEST_OBJ := $(OUT_DIR)/bank_switch_checksum_test.o
SWITCH_TEST_ROM := $(ROM_DIR)/BANK_SWITCH_CHECKSUM_TEST.ROM
SWITCH_TEST_MAP := $(OUT_DIR)/BANK_SWITCH_CHECKSUM_TEST.map
SWITCH_TEST_LBL := $(OUT_DIR)/BANK_SWITCH_CHECKSUM_TEST.lbl

.PHONY: all build build-switch-test run run-switch-test clean toolcheck test-p6 p6-roms

all: build

toolcheck:
	@command -v $(CA65) >/dev/null || (echo "error: $(CA65) not found (install cc65)" >&2; exit 1)
	@command -v $(LD65) >/dev/null || (echo "error: $(LD65) not found (install cc65)" >&2; exit 1)

$(OUT_DIR):
	mkdir -p $(OUT_DIR)

$(ROM_DIR):
	mkdir -p $(ROM_DIR)

$(OUT_DIR)/%.o: $(ROOT)asm/%.asm $(wildcard $(ROOT)asm/*.inc) | $(OUT_DIR)
	$(CA65) -t none -g -o $@ $<

$(ROM): $(OBJ) $(CFG) | $(ROM_DIR)
	$(LD65) -C $(CFG) -o $@ $(OBJ) -m $(MAP) -Ln $(LBL)

$(SWITCH_TEST_OBJ): $(SWITCH_TEST_SRC) $(wildcard $(ROOT)asm/*.inc) | $(OUT_DIR)
	$(CA65) -t none -g -o $@ $<

$(SWITCH_TEST_ROM): $(SWITCH_TEST_OBJ) $(CFG) | $(ROM_DIR)
	$(LD65) -C $(CFG) -o $@ $(SWITCH_TEST_OBJ) -m $(SWITCH_TEST_MAP) -Ln $(SWITCH_TEST_LBL)

$(CHECKSUM_FILE): $(ROM) | $(ROM_DIR)
	@crc_hex="$$(python3 -c 'import zlib,sys; d=open(sys.argv[1], "rb").read(); print(f"{zlib.crc32(d)&0xffffffff:08x}")' "$(ROM)")"; \
	sha1_hex="$$(shasum -a 1 "$(ROM)" | awk '{print $$1}')"; \
	line="R$${crc_hex}S$${sha1_hex}"; \
	{ \
		echo "# Auto-generated by make. Do not edit."; \
		echo "32-0349-b.128 $${line}"; \
		echo "APPLE2E.ROM $${line}"; \
		echo "EVER2E.ROM $${line}"; \
	} > "$(CHECKSUM_FILE)"

build: toolcheck $(ROM) $(CHECKSUM_FILE)
	@$(MAKE) p6-roms
	@echo "built: $(ROM)"
	@echo "map:   $(MAP)"
	@echo "labels:$(LBL)"
	@echo "checksums:$(CHECKSUM_FILE)"

build-switch-test: toolcheck $(SWITCH_TEST_ROM)
	@echo "built: $(SWITCH_TEST_ROM)"
	@echo "map:   $(SWITCH_TEST_MAP)"
	@echo "labels:$(SWITCH_TEST_LBL)"

run: build
	cd $(JVM_DIR) && ./gradlew run --args="$(PROFILE) $(ARGS)"

run-switch-test: build-switch-test
	cd $(JVM_DIR) && ./gradlew run --args="$(SWITCH_TEST_PROFILE) $(ARGS)"

.PHONY: test-p6-precheck test-p6-py test-p6-jvm

p6-roms: | $(ROM_DIR)
	python3 scripts/build_diskii_p6_custom.py \
		--out "$(ROM_DIR)/DISKII_P6_CUSTOM.rom" \
		--stock-out "$(ROM_DIR)/DISKII_P6_STOCK.rom"

# Fast local guardrail.
test-p6-precheck: p6-roms
	python3 -m unittest tests.test_diskii_p6_entrypoints

# Python-side fixture + output/timing report.
test-p6-py:
	@if [ -d "$(PY_DIR)" ] && [ -d "$(PY_DIR)/tests" ] && [ -f "$(PY_DIR)/tools/check_hello_bootstrap_output.py" ]; then \
		cd $(PY_DIR) && python3 -m unittest discover -s tests -p 'test_bootstrap_disk_fixture.py'; \
		cd $(PY_DIR) && if [ "$(P6_PY_STRICT)" = "1" ]; then \
			python3 tools/check_hello_bootstrap_output.py --report "$(P6_PY_REPORT)" --strict; \
		else \
			python3 tools/check_hello_bootstrap_output.py --report "$(P6_PY_REPORT)"; \
		fi; \
	elif [ -d "$(PY_DIR)" ]; then \
		echo "skip test-p6-py: required files not found under $(PY_DIR)"; \
	else \
		echo "skip test-p6-py: $(PY_DIR) not present"; \
	fi

# Authoritative gate: JVM regression suite.
test-p6-jvm:
	cd $(JVM_DIR) && if [ -n "$(JVM_P6_DISK_FILTER)" ] && [ -f src/test/device/DiskIISlotRomSignatureTest.java ]; then \
		./gradlew test --tests $(JVM_P6_TEST_FILTER) --tests $(JVM_P6_DISK_FILTER); \
	else \
		./gradlew test --tests $(JVM_P6_TEST_FILTER); \
	fi

# One command runs both, in order.
test-p6: test-p6-precheck test-p6-py test-p6-jvm

clean:
	rm -rf $(OUT_DIR)
