CA65 ?= ca65
LD65 ?= ld65

ROOT := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
OUT_DIR := $(ROOT)build
ROM_DIR := $(ROOT)ROMS
PROFILE := $(ROOT)profiles/Apple2eEver2eBootLoopNoSlots.emu
JVM_DIR ?= /Users/shane/app/ever2e

ASM_SRC := \
	$(ROOT)asm/main.asm \
	$(ROOT)asm/babeep.asm \
	$(ROOT)asm/cpu_guard.asm \
	$(ROOT)asm/softswitch_reset.asm \
	$(ROOT)asm/ram_clear_unrolled.asm
OBJ := \
	$(OUT_DIR)/main.o \
	$(OUT_DIR)/babeep.o \
	$(OUT_DIR)/cpu_guard.o \
	$(OUT_DIR)/softswitch_reset.o \
	$(OUT_DIR)/ram_clear_unrolled.o
CFG := $(ROOT)cfg/apple2e_rom16k.cfg
ROM := $(ROM_DIR)/EVER2E.ROM
MAP := $(OUT_DIR)/EVER2E.map
LBL := $(OUT_DIR)/EVER2E.lbl
CHECKSUM_FILE := $(ROM_DIR)/checksum.txt

.PHONY: all build run clean toolcheck

all: build

toolcheck:
	@command -v $(CA65) >/dev/null || (echo "error: $(CA65) not found (install cc65)" >&2; exit 1)
	@command -v $(LD65) >/dev/null || (echo "error: $(LD65) not found (install cc65)" >&2; exit 1)

$(OUT_DIR):
	mkdir -p $(OUT_DIR)

$(ROM_DIR):
	mkdir -p $(ROM_DIR)

$(OUT_DIR)/%.o: $(ROOT)asm/%.asm | $(OUT_DIR)
	$(CA65) -t none -g -o $@ $<

$(ROM): $(OBJ) $(CFG) | $(ROM_DIR)
	$(LD65) -C $(CFG) -o $@ $(OBJ) -m $(MAP) -Ln $(LBL)

$(CHECKSUM_FILE): $(ROM) | $(ROM_DIR)
	@crc_hex="$$(python3 -c 'import zlib,sys; d=open(sys.argv[1], "rb").read(); print(f"{zlib.crc32(d)&0xffffffff:08x}")' "$(ROM)")"; \
	sha1_hex="$$(shasum -a 1 "$(ROM)" | awk '{print $$1}')"; \
	line="R$${crc_hex}S$${sha1_hex}"; \
	{ \
		echo "# Auto-generated by make. Do not edit."; \
		echo "32-0349-b.128 $${line}"; \
		echo "APPLE2E.ROM $${line}"; \
		echo "EVER2E.ROM $${line}"; \
	} > "$(CHECKSUM_FILE)"

build: toolcheck $(ROM) $(CHECKSUM_FILE)
	@echo "built: $(ROM)"
	@echo "map:   $(MAP)"
	@echo "labels:$(LBL)"
	@echo "checksums:$(CHECKSUM_FILE)"

run: build
	cd $(JVM_DIR) && ./gradlew run --args="$(PROFILE) $(ARGS)"

clean:
	rm -rf $(OUT_DIR)
